//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataflip.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataflip.Cli.DefaultFiles", typeof(DefaultFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;contexts&quot; :
        ///	[
        ///		{
        ///			&quot;connectionString&quot; : &quot;ENTER YOUR CONNECTION STRING HERE (REQUIRED)&quot;,
        ///			&quot;namespace&quot; : &quot;ENTER THE NAMESPACE FOR THE CONTEXT (REQUIRED)&quot;,
        ///			&quot;name&quot; : &quot;ENTER THE NAME OF THE CONTEXT CLASS (REQUIRED)&quot;,
        ///			&quot;output&quot; : &quot;ENTER THE FILENAME TO WRITE THE CONTEXT CLASSES, RELATIVE PATHS ARE ALLOWED&quot;,
        ///			&quot;sprocs&quot; : 
        ///				[
        ///					/* Example 1. A sproc that returns data in multiple columns.*/
        ///					{
        ///						/*[OPTIONAL] Creates a ///&lt;summary&gt; section over the method with a comment.*/
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultDataflipJson {
            get {
                return ResourceManager.GetString("DefaultDataflipJson", resourceCulture);
            }
        }
    }
}
